### ISSUE TITLE
Fixme: We should go sogang coin karaoke

### ISSUE THREAD

**Issue by JimJeon** [codingbowoo/codingbowoo-resource#3]
크리스마스 캐롤 모임이 성공적이지 못했다... 우리는 간다 다시금 서강코노! @itsnamgyu @codingbowoo

**Comment by codingbowoo** [comment]
@JimJeon @itsnamgyu 가 2월 말 출국 예정입니다. 일정이 정해질 때 까지 해당 이슈는 열어두겠습니다.

**Comment by itsnamgyu** [comment]
언제갑니까!!

**Comment by codingbowoo** [comment]
다녀왔으므로 닫습니다!
