### ISSUE TITLE
외국말 나는 싫다. 좋다 한국말. 

### ISSUE THREAD

**Issue by dbdydgur2244** [codingbowoo/codingbowoo-resource#5]
한국말. 나는 애용한다
회식있었다 점심에.
싫다 세미나. 준비안했다 오늘도.......

**Comment by codingbowoo** [comment]
@dbdydgur2244 의 세미나가 끝날 때까지 해당 이슈는 열어두겠습니다.

**Comment by codingbowoo** [comment]
영영 끝나지 않는 것은 아니겠지... (먼산)

**Comment by dbdydgur2244** [comment]
![forever](https://i.ytimg.com/vi/2CyP3hAOy0g/maxresdefault.jpg)

**Comment by taeguk** [comment]
애용 나도 한국말 한다.
금요일한다 야근에
주말은 러스트이다 내일해야지.

**Comment by taeguk** [comment]
흑흑흑 야근중

**Comment by codingbowoo** [comment]
@dbdydgur2244 의 세미나가 끝나지 않았다...?

**Comment by dbdydgur2244** [comment]
@codingbowoo  앗,,,아,,아,, 끝났지요
